# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.1.1

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

def read_readme():
    with open('README.md') as f:
        return f.read()

NAME = "giteapy"
VERSION = "1.22.0"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi>=2017.4.17",
    "python-dateutil>=2.1",
    "six>=1.10",
    "urllib3>=1.23"
]

setup(
    name=NAME,
    version=VERSION,
    description="Python SDK for Gitea - A painless, self-hosted Git service",
    author_email="gnpaone@gmail.com",
    url="https://github.com/gnpaone/giteapy",
    keywords=["gitea", "git", "swagger"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description=read_readme(),
    long_description_content_type="text/markdown",

    classifiers=[
          'Programming Language :: Python',
          'Programming Language :: Python :: 2',
          'Programming Language :: Python :: 3',
          'Operating System :: OS Independent',
          'Intended Audience :: Developers',
      ],
)
