name: Create tag

on:
  workflow_dispatch:
  # workflow_run:
  #   workflows: ["Sync repo"]
  #   types:
  #     - completed

jobs:
  check-and-create:
    runs-on: ubuntu-latest
    steps:
      - name: Find latest tag of source repo
        uses: oprypin/find-latest-tag@v1
        with:
          repository: mg-cloud/giteapy
          regex: '^\d+\.\d+\.\d+$'
        id: sourcetag

      # - name: Find latest tag of target repo
      #   uses: oprypin/find-latest-tag@v1
      #   with:
      #     repository: gnpaone/giteapy
      #   id: targettag

      - run: npm install semver

      # - name: Check for new tag
      #   uses: actions/github-script@v7
      #   id: tag-chk
      #   with:
      #     script: |
      #       const semver = require('semver');

      #       const ver1 = `${{ steps.sourcetag.outputs.tag }}`;
      #       const ver2 = `${{ steps.targettag.outputs.tag }}`;

      #       if (semver.gt(ver1, ver2)) {
      #         core.setOutput('create_tag', true);
      #       } else {
      #         core.setOutput('create_tag', false);
      #       }

      - name: Trigger tag creation
        # if: steps.tag-chk.outputs.create_tag == 'true'
        uses: qoomon/actions--create-tag@v1.0.0
        with:
          name: ${{ steps.sourcetag.outputs.tag }}

      - run: git push origin ${{ steps.sourcetag.outputs.tag }}
          
