name: Create tag

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Sync repo"]
    types:
      - completed

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      sourcetag: ${{ steps.sourcetag.outputs.tag }}
      create_tag: ${{ steps.tag-chk.outputs.create_tag }}
    steps:
      - name: Find latest tag of source repo
        uses: oprypin/find-latest-tag@v1
        with:
          repository: mg-cloud/giteapy
          regex: '^\d+\.\d+\.\d+$'
        id: sourcetag

      - name: Find latest tag of target repo
        uses: oprypin/find-latest-tag@v1
        with:
          repository: gnpaone/giteapy
        id: targettag

      - run: npm install semver

      - name: Check for new tag
        uses: actions/github-script@v7
        id: tag-chk
        with:
          script: |
            const semver = require('semver');

            const ver1 = `${{ steps.sourcetag.outputs.tag }}`;
            const ver2 = `${{ steps.targettag.outputs.tag }}`;

            if (semver.gt(ver1, ver2)) {
              core.setOutput('create_tag', true);
            } else {
              core.setOutput('create_tag', false);
            }

  update:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.create_tag == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Update version in setup.py
        run: sed -i 's/VERSION = "[^"]*"/VERSION = "${{ needs.check.outputs.sourcetag }}"/' setup.py

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update package version"
          committer: gnpaone <78990165+gnpaone@users.noreply.github.com>
          author: gnpaone <78990165+gnpaone@users.noreply.github.com>
          branch: version-update
          base: master
          add-paths: setup.py
          title: Bump python package version
          labels: ":mag_right: bump"

      - name: Enable pull request automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}

      - name: Delete PRs head branch
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          numbers: ${{ steps.cpr.outputs.pull-request-number }}

  create:
    runs-on: ubuntu-latest
    needs: [check, update]
    if: needs.check.outputs.create_tag == 'true'
    steps:
      - name: Get last commit
        id: lastcommit
        uses: nmbgeek/github-action-get-latest-commit@v0.1.0
        with:
          repository: gnpaone/giteapy
          branch: master
          
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.lastcommit.outputs.hash }}

      - name: Trigger tag creation
        uses: qoomon/actions--create-tag@v1.0.0
        with:
          name: ${{ needs.check.outputs.sourcetag }}

      - run: git push origin ${{ needs.check.outputs.sourcetag }}
